name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Chạy hàng ngày vào 00:00 UTC
  workflow_dispatch:     # Cho phép chạy workflow thủ công

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: phananhtu1998  # Thay username của bạn
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update snake contribution graph"
          branch: output
